<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Contoso.Invoicing.Application</RootNamespace>
    <AssemblyName>Contoso.Invoicing.Application</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Description>Application services for Contoso Finance Batch Invoicing</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoicing.Domain\Invoicing.Domain.csproj" />
  </ItemGroup>

</Project>
